### ISSUE TITLE
Erratas

### ISSUE THREAD

**Issue by sergiogragera** [the-managers-manual/issues#1]
Referencio las páginas en formato PDF:

- Página 9: "en si mismo" -> "en **sí** mismo"
- Página 9: "haciendo un buen trabajo?." -> "haciendo un buen trabajo?"
- Página 14: " y de él que te das cuenta" -> y **del** que te das cuenta"
- Página 21: "¿sabes qué más tiene?." -> "¿sabes qué más **tiene?**"
- Página 21: "exponencialmente?, ¿Bajarán los..." -> "exponencialmente?, ¿**bajarán** los..."
- Página 23: "cuando se que estoy en lo cierto" -> "cuando **sé** que estoy en lo cierto"
- Página 23: " identificar que mejorar" -> " identificar **qué** mejorar"
- Página 26: "preparar el feedback ¿qué harías" -> "preparar el **feedback. ¿Qué** harías"
- Página 26: "la razón de hacerlo ¿por qué..." -> "la razón de **hacerlo. ¿Por** qué..."
- Página 29: "añadir como mejorar esas partes" -> "añadir **cómo** mejorar esas partes."
- Página 30: "Hemos de asegurarnos eso sí que" -> "Hemos de asegurarnos**, eso sí,** que"
- Página 30: "directamente, ¿Hay" -> "**directamente.** ¿Hay"
- Página 30: "Cómo managers podemos" -> "**Como** managers podemos"
- Página 33: "nosotros mismos, que de la otra persona" -> "nosotros mismos que de la otra persona"
- Página 37: "importancia que estes alineado" -> "importancia que **estés** alineado"
- Página 40: "no a el usuario" -> "no **al** usuario"
- Página 41: "en base a el feedback" -> "en base **al** feedback"
- Página 42: "de pago o Open Source" -> "de pago **u** Open Source"
- Página 45: "a sigan sus instrucciones" -> "a **que** sigan sus instrucciones"
- Página 46: "convencidos como tu" -> "convencidos como **tú**"
- Página 46: "ingenieros e Engineering Managers" -> "ingenieros **y** Engineering Managers"
- Página 47: "tu mismo" -> "**tú** mismo"
- Página 47: "ellas mismos" -> "ellas **mismas**"
- Página 48: "cuando lo haces" -> "**cuándo** lo haces"
- Página 50: "tu como manager" -> "**tú** como manager"
- Página 55: "empresa, ¿No deberíamos" -> "**empresa.** ¿No deberíamos"
- Página 62: "cada Viernes" -> "cada **viernes**"
- Página 62: "querémos saber que" -> "**queremos** saber **qué**"

**Comment by keyvanakbary** [comment]
¡Muchas gracias Sergio! te he incluido en la sección de agradecimientos para la próxima publicación :)
