### ISSUE TITLE
Typos en Índice, Prefacio y Sobre los autores

### ISSUE THREAD

**Issue by mpcr** [the-managers-manual/issues#10]
- Índice al final: ¿Fín? --> ¿**Fin**? (monosílabo, sin tilde)
- Prefacio iii: 
Este libro no esta finalizado, la edición sobre la plataforma Leanpub
no es una publicación tradicional al uso. El contenido del libro
esta vivo y hasta que se cierre de forma definitiva, nuevos capítulos
y cambios serán publicados de forma contínua. -->
Este libro no **está** (lleva tilde, verbo en tercera persona) finalizado, la edición [...] contenido del libro
**está** (lleva tilde, verbo en tercera persona) vivo **y,** (falta coma inicial para delimitar la aclaración) hasta que se cierre de forma definitiva, nuevos capítulos y cambios serán publicados de forma **continua**. (palabra llana, no lleva tilde).
- Agradecimientos, sobre la portada: 
[...] diseñador Carlos Tallón ¡Muchísimas gracias! --> diseñador Carlos **Tallón.** ¡Muchísimas gracias! (signo de puntuación para separar las oraciones)
- Sobre los autores, Keyvan: ya reportado en esta [issue](https://github.com/the-managers-manual/issues/issues/9)
- Sobre los autores, Félix: 
Ha experimentado todo tipo de topologías
organizacionales, startups, empresas de alto crecimiento o
grandes corporaciones como Google. En las cuales ha desempeñado
una gran variedad de roles, desde ser el primer empleado de una
startup a diversos puestos de liderazgo como Tech Lead, CTO y
Engineering Manager. Lo que le da una amplía experiencia en todo
tipo de entornos y circustancias, tanto éxitos como fracasos. 
Puedes seguirle en Twitter, en LinkedIn, en su Blog o en GitHub -->
Ha experimentado todo tipo de topologías
organizacionales, startups, empresas de alto crecimiento o
grandes corporaciones como **Google, en** (frase subordinada mejor separada por coma que por punto y seguido en castellano) las cuales ha desempeñado
una gran variedad de roles, desde ser el primer empleado de una
startup a diversos puestos de liderazgo como Tech Lead, CTO y
Engineering **Manager, lo** (frase subordinada mejor separada por coma que por punto y seguido en castellano) que le da una **amplia** (es el adjetivo no el verbo, no lleva tilde, palabra llana) experiencia en todo
tipo de entornos y **circunstancias** (misspelling), tanto éxitos como fracasos. 
Puedes seguirle en Twitter, en LinkedIn, en su Blog o en **GitHub.** (faltaba el punto de cierre)
- Sobre los autores, Álvaro: 
Puedes seguirle en Twitter, en LinkedIn, en su Blog o en **GitHub.** (faltaba el punto de cierre)

**Comment by keyvanakbary** [comment]
Muchísimas gracias Pilar, queda corregido para la siguiente versión del libro :slightly_smiling_face: Por tu generosa aportación, te incluyo como colaboradora en la parte de agradecimientos :raised_hands:
