### ISSUE TITLE
Uso de rayas para aclaraciones

### ISSUE THREAD

**Issue by sergiogragera** [the-managers-manual/issues#3]
Sobran espacios entre la raya y la primera palabra, y entre la útlima palabra y la raya final: páginas 5, 6, 12, 14, 15, 18, etc.

[RAE](https://www.rae.es/dpd/raya) "Cuando se usan dos rayas [...] estas se escriben pegadas a la primera y a la última palabra del período que enmarcan".

Además, en la página 40 se usa guion en lugar de raya: "comprado por su empresa - el tipo" cuando debería ser "comprado por su **empresa —el** tipo".

[RAE](https://www.rae.es/dpd/raya) "Signo de puntuación representado por un trazo horizontal (—) de mayor longitud que el correspondiente al guion (-)"

**Comment by keyvanakbary** [comment]
Corregido :fire: ¡Muchas gracias!
