### ISSUE TITLE
Tratamiento de los extranjerismos

### ISSUE THREAD

**Issue by sergiogragera** [the-managers-manual/issues#4]
Palabras como _feedback_, _manager_ (si se hace uso de la voz inglesa sin acentuar), _pull request_, etc., deben resaltarse con cursiva o comillas.

Según el [diccionario panhispánico de dudas](https://www.rae.es/dpd/ayuda/tratamiento-de-los-extranjerismos):

2.1. Mantenimiento de la grafía y pronunciación originarias [...] de la obligación de escribirlos con resalte tipográfico (cursiva o comillas) para señalar su carácter ajeno a la ortografía del español.

**Comment by mpcr** [comment]
De hecho, en algún pasaje ya lo usan, Sobre los autores (página vi), donde citan _personal shopping_: 

Actualmente Álvaro es VP de Ingeniería en la empresa líder en
_personal shopping_ en Europa, Lookiero.

Se debería optar por un criterio único para reflejar los anglicismos.

**Comment by keyvanakbary** [comment]
Muchísimas gracias, ¡corregido! :raised_hands:
