### ISSUE TITLE
Growth mindset

### ISSUE THREAD

**Issue by javichur** [the-managers-manual/issues#5]
Como sugerencia, se podría añadir una breve definición de "Growth Mindset" la primera vez que se utiliza este término.

Aparece por primera vez aquí pero se menciona como si fuera un concepto ya conocido:

"Ya hemos hablado de los beneficios de incentivar el growth mindset en la gente, pero esto cobra especial importancia cuando hablamos de feedback."

Gracias!

**Comment by keyvanakbary** [comment]
Muchas gracias Javier, esa frase se nos ha colado adelantando un tema del efectivamente aún no hemos hablado. La hemos eliminado hasta que tengamos el tema preparado. ¡Gracias de nuevo!
