### ISSUE TITLE
Feedback prefacio + el rol del manager

### ISSUE THREAD

**Issue by vgaltes** [the-managers-manual/issues#6]
En el prefacio habláis de VP de Engineering y en la bio de Alvaro habláis de VP de Ingeniería.

La oportunidad
- Empieza la cabeza a darle vueltas. No seria a darte vueltas?
- Tener interés por los siguientes aspectos puede ser una señal positiva para el cambio → falta el punto final.

Utilizáis manager con mayúscula y con minúscula

pero ¿sabes qué más tiene?. Carencias → hay que poner ese punto enmedio?

**Comment by keyvanakbary** [comment]
Ya esta casi todo esto corregido de issues anteriores. Muy fino lo de "darle vueltas"; lo acabo de corregir :smiley: ¡Muchas gracias de Vicenç!
