### ISSUE TITLE
Estructura de frase: orden del adverbio "también"

### ISSUE THREAD

**Issue by islomar** [the-managers-manual/issues#8]
En el apartado "Audiencia del libro", escribís al final "la temática es suficientemente detallada como para ser de interés para las más veteranas en el rol **también**".

Ese adverbio "también" al final de la frase creo que es un tanto extraño en español, creo que sería más natural algo así como "la temática es suficientemente detallada como para **también** ser de interés para las más veteranas en el rol" o incluso "para ser **también** de interés...".

**Comment by keyvanakbary** [comment]
Muchas gracias Isidro, tienes razón que suena extraño. ¡Aplicamos la sugerencia! :raised_hands:
