### ISSUE TITLE
Tildes en presentación de Keyvan: "fin", "sí", "distribuido"

### ISSUE THREAD

**Issue by islomar** [the-managers-manual/issues#9]
En la presentación de Keyvan, escribis "y no como el **fín** en **si** mismo".

En esa frase, "fin" no debería llevar acento, pero sí "sí", quedando: "y no como el **fin** en **sí** mismo".

Por otra parte, "distribuidos" no lleva acento (aparece en "gran interés en el ámbito técnico en sistemas **distribuídos**").

**Comment by keyvanakbary** [comment]
¡Muchas gracias Isidro! Queda corregido para la siguiente versión :hugs:
